"""
Meta-layer schemas for ml-service2.0.

These schemas cover the MetaDecisionEngine's input/output contracts:

    NewsSignal             — FinGPT/FinBERT news sentiment for a single instrument.
    ConfidenceDecomposition — Five-component breakdown of the final confidence score.
    MetaOutputExplainability — XAI breakdown attached to every MetaOutput.
    MetaOutput             — The final trading decision produced by MetaDecisionEngine.
    MetaDecideRequest      — Input to POST /v2/meta/decide.
    OOSRecord              — Single OOS record for meta-layer calibrator retraining.
    MetaFitResponse        — Response from POST /v2/meta/fit.

All schemas inherit from BaseSchema (Pydantic V2, strict=True, frozen=True).

Validates: Requirements 10.1, 10.8, 19.2
"""
from __future__ import annotations

from datetime import datetime
from typing import Literal, Optional

from pydantic import Field

from src.schemas.base import BaseSchema, PredictionProvenance


class NewsSignal(BaseSchema):
    """FinGPT/FinBERT news sentiment signal for a single instrument.

    ``direction`` encodes the market impact:
        -1  BEARISH
         0  NEUTRAL
        +1  BULLISH

    ``rationale`` is capped at 200 characters (≈ 30 words) to keep API
    response payloads compact and to match the LLM output constraint
    documented in the design.
    """

    direction: Literal[-1, 0, 1]
    confidence: float = Field(ge=0.0, le=1.0)
    rationale: str = Field(default="", max_length=200)


class ConfidenceDecomposition(BaseSchema):
    """Five-component breakdown of the MetaDecisionEngine final confidence score.

    Each component is bounded to [0, 1] so downstream consumers can display
    normalised importance bars without additional clamping.
    """

    base_confidence: float = Field(ge=0.0, le=1.0)
    calibration_quality: float = Field(ge=0.0, le=1.0)
    agreement_bonus: float = Field(ge=0.0, le=1.0)
    data_quality_factor: float = Field(ge=0.0, le=1.0)
    regime_confidence_factor: float = Field(ge=0.0, le=1.0)


class MetaOutputExplainability(BaseSchema):
    """XAI breakdown attached to every MetaOutput.

    ``top_features``      — up to 5 highest-impact features across all contributing models.
    ``conflicting_models`` — model names whose direction signal contradicts the ensemble.
    ``rationale``          — ≤ 50-word natural language summary generated by the LLM reasoner.
    """

    top_features: list[str] = Field(default_factory=list)
    conflicting_models: list[str] = Field(default_factory=list)
    rationale: str = ""


class MetaOutput(BaseSchema):
    """Final trading decision produced by the MetaDecisionEngine.

    The engine aggregates RegimeClassifier, StockRanker, StrategySelector,
    RiskPredictor, and RLExecutionAgent outputs via regime-aware ensemble
    weighting, Platt/isotonic calibration, and an AbstentionPolicy that
    guards live capital deployment.

    ``provenance`` reflects the weakest-link provenance across all
    contributing models (TRAINED_MODEL > HEURISTIC > INSUFFICIENT_EVIDENCE
    > UNAVAILABLE).  Only TRAINED_MODEL provenance is eligible for live
    capital deployment.
    """

    # ── Core decision ─────────────────────────────────────────────────────────
    action: Literal["BUY", "SELL", "WAIT", "NO_TRADE"]
    confidence: float = Field(ge=0.0, le=1.0)
    uncertainty: float = Field(ge=0.0, le=1.0)  # confidence + uncertainty should be <= 1.0
    agreement: float = Field(ge=0.0, le=1.0)  # overall agreement score across model families
    agreement_ratio: float = Field(ge=0.0, le=1.0)  # fraction of models agreeing on direction

    # ── Ensemble ─────────────────────────────────────────────────────────────
    ensemble_score: float = 0.0
    reason_codes: list[str] = Field(default_factory=list)
    contributing_models: list[str] = Field(default_factory=list)
    abstention: bool = False

    # ── Sub-components ────────────────────────────────────────────────────────
    provenance: PredictionProvenance = PredictionProvenance.UNAVAILABLE
    news_sentiment_signal: Optional[NewsSignal] = None
    decomposition: Optional[ConfidenceDecomposition] = None
    explainability: Optional[MetaOutputExplainability] = None

    # ── Request tracing ───────────────────────────────────────────────────────
    request_id: str = ""
    symbol: str = ""
    timestamp: Optional[datetime] = None
    latency_ms: float = 0.0


class MetaDecideRequest(BaseSchema):
    """Input to POST /v2/meta/decide.

    ``regime`` is the string value of a ``MarketRegime`` enum member
    (e.g. "strong_bull", "crash").  A string rather than the enum type
    is used here so that this schema can be constructed without importing
    the full MarketRegime enum in every consumer module.

    ``force_refresh_news`` bypasses the 60-second LLM news cache and
    triggers a fresh FinGPT/FinBERT inference call.
    """

    symbol: str
    regime: str  # MarketRegime value — validated at runtime by the engine
    force_refresh_news: bool = False


class OOSRecord(BaseSchema):
    """A single out-of-sample prediction record for meta-layer calibrator retraining.

    Submitted in batches of ≥ 30 to POST /v2/meta/fit.  The calibration
    layer uses these records to refit Platt scaling or isotonic regression
    for each base model, reducing ECE on live production data.
    """

    model_id: str
    raw_score: float
    realized_outcome: float  # 1.0 = correct / target hit, 0.0 = incorrect, or actual return
    timestamp: datetime


class MetaFitResponse(BaseSchema):
    """Response from POST /v2/meta/fit.

    Summarises which calibrators were updated and how many OOS records were
    consumed.  ``success=False`` with a populated ``message`` indicates that
    the minimum record threshold was not met or a calibration failure occurred.
    """

    calibrators_updated: int = 0
    records_used: int = 0
    success: bool
    message: str = ""
